from pathlib import Path
R=Path(__file__).resolve().parents[1]
def m(rel,name,body):
 p=R/rel;t=p.read_text();i=t.find(name+'(');s=t.rfind('    @Test',0,i);e=t.find('\n    @Test',i);e=e if e>=0 else t.rfind('\n}');
 if i<0 or s<0 or e<=s: raise RuntimeError((rel,name,i,s,e))
 p.write_text(t[:s]+body.rstrip()+'\n'+t[e:])
B='src/test/java/com/hellovoid/liquiddock/'
m(B+'DockGlassSceneContractTest.java','dockItemsUseOneDockCompositorAndNeverWorkspaceStaticNodes','''    @Test public void dockItemsUseOneDockCompositorAndNeverWorkspaceStaticNodes() throws Exception {
 String c=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/DockGlassCompositor.java")); String n=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/DockGlassItemNode.java"));
 assertTrue(c.contains("ONE_OUTPUT_SWAP")&&c.contains("drawDockBody")&&c.contains("drawItem")&&c.contains("volatile DockGlassSceneSnapshot latestScene")); assertFalse(n.contains("TextureView")||n.contains("EGLSurface")||n.contains("LauncherGlassStaticNode"));
    }''')
m(B+'DockGlassSceneContractTest.java','dockUiPublishesImmutableSceneSnapshotBeforeGlDraw','''    @Test public void dockUiPublishesImmutableSceneSnapshotBeforeGlDraw() throws Exception {
 String c=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/DockGlassCompositor.java")); String v=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/Miuix307PassBlurTextureView.java"));
 assertTrue(c.contains("refreshUiSceneIfNeeded")&&c.contains("DockGlassSceneSnapshot latestScene()")); assertTrue(v.contains("dockCompositor.refreshUiSceneIfNeeded(")&&v.contains("dockCompositor.latestScene()")); String d=c.substring(c.indexOf("int drawFrame(")); assertFalse(d.contains("transformMatrixToGlobal")||d.contains(".capture(")||d.contains("snapshotForRoot"));
    }''')
m(B+'FolderGlassToggleContractTest.java','folderGlassHasIndependentDefaultOnConfigAndRuntimeGate','''    @Test public void folderGlassHasIndependentDefaultOnConfigAndRuntimeGate() throws Exception {
 String s=read("src/main/java/com/hellovoid/liquiddock/config/ConfigSchema.java"),r=read("src/main/java/com/hellovoid/liquiddock/LiquidDockConfig.java"),h=read("src/main/java/com/hellovoid/liquiddock/MiuixFolderGlassHook.java");
 assertTrue(s.contains("SMALL_FOLDER_GLASS = bool(")&&s.contains("LARGE_FOLDER_GLASS = bool(")); assertTrue(r.contains("GlassComponentStyle smallFolderStyle")&&r.contains("GlassComponentStyle largeFolderStyle")&&r.contains(": legacyFolderEnabled")); assertTrue(h.contains("smallFolder ? glassConfig.smallFolderStyle : glassConfig.largeFolderStyle"));
    }''')
m(B+'FolderGlassToggleContractTest.java','liquidSettingsExposeFolderGlassSwitchUnderMasterGlassSwitch','''    @Test public void liquidSettingsExposeFolderGlassSwitchUnderMasterGlassSwitch() throws Exception {
 String u=read("src/main/kotlin/com/hellovoid/liquiddock/ComposeSettingsActivity.kt"); assertTrue(u.contains("ConfigSchema.Glass.SMALL_FOLDER_GLASS")&&u.contains("ConfigSchema.Glass.LARGE_FOLDER_GLASS")&&u.contains("smallFolderGlass")&&u.contains("largeFolderGlass"));
    }''')
m(B+'LauncherGlassAlignmentAndRadiusTest.java','folderRadiusIsPersistedAndSharedByStaticAndDragGlass','''    @Test public void folderRadiusIsPersistedPerCanonicalFolderKind() throws Exception {
 String s=read("src/main/java/com/hellovoid/liquiddock/config/ConfigSchema.java"),r=read("src/main/java/com/hellovoid/liquiddock/LiquidDockConfig.java"),f=read("src/main/java/com/hellovoid/liquiddock/MiuixFolderGlassHook.java"); assertTrue(s.contains("SMALL_FOLDER_CORNER_RADIUS")&&s.contains("LARGE_FOLDER_CORNER_RADIUS")); assertTrue(r.contains("smallFolderStyle = new GlassComponentStyle")&&r.contains("largeFolderStyle = new GlassComponentStyle")); assertTrue(f.contains("smallFolder ? glassConfig.smallFolderStyle : glassConfig.largeFolderStyle"));
    }''')
m(B+'LauncherGlassAlignmentAndRadiusTest.java','composeAndLegacyGuiExposeFolderRadiusWithFolderDependency','''    @Test public void composeAndLegacyGuiExposePerKindFolderStyleControls() throws Exception {
 String c=read("src/main/kotlin/com/hellovoid/liquiddock/ComposeSettingsActivity.kt"),x=read("src/main/res/xml/preferences.xml"); assertTrue(c.contains("SMALL_FOLDER_SIZE_OFFSET")&&c.contains("SMALL_FOLDER_CORNER_RADIUS")&&c.contains("LARGE_FOLDER_SIZE_OFFSET")&&c.contains("LARGE_FOLDER_CORNER_RADIUS")); assertTrue(x.contains("liquid_small_folder_corner_radius")&&x.contains("liquid_large_folder_corner_radius"));
    }''')
m(B+'LauncherGlassBackdropCacheContractTest.java','interactionRedrawDoesNotRebuildNormalizationAndBlur','''    @Test public void interactionRedrawDoesNotRebuildNormalizationAndBlur() throws Exception {
 String s=Files.readString(SESSION); assertTrue(s.contains("boolean backdropDirty = work.rebuildBackdrop || sourceChanged || !backdropPrepared;")&&s.contains("renderScene(backdropDirty, staticDirty, dragDirty);")&&s.contains("private void renderScene(boolean rebuildBackdrop, boolean renderStatic, boolean renderDrag)")&&s.contains("prismalRenderer.prepareBackdrop(rawTexture, rootWidth, rootHeight, params);"));
    }''')
m(B+'Miuix307GlassCustomizationContractTest.java','everyVisibleZeroCopyOpticalUniformIsActuallyConsumed','''    @Test public void everyVisibleZeroCopyOpticalUniformIsActuallyConsumed() throws Exception {
 String mat=Files.readString(MAIN.resolve("Miuix307PrismalMaterial.java")),v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")); assertTrue(mat.contains("glass.blur")&&mat.contains("glass.ior")&&mat.contains("glass.prismalTransmittance")); assertTrue(v.contains("Miuix307PrismalAdapter.toPortable(opticalParams)")&&v.contains("prismalRenderer.prepareBackdrop(")&&v.contains("dockCompositor.drawFrame("));
    }''')
m(B+'Miuix307PassBlurGpuDemoTest.java','activeRendererUsesTextureViewEgl','''    @Test public void activeRendererUsesTextureViewEgl() throws Exception {
 String r=Files.readString(MAIN.resolve("Miuix307ZeroCopyRenderer.java")),v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")); assertTrue(r.contains("new Miuix307PassBlurTextureView")); assertTrue(v.contains("extends TextureView")&&v.contains("eglCreateWindowSurface")&&v.contains("GL_TEXTURE_EXTERNAL_OES")&&v.contains("renderNormalizationPass")&&v.contains("prismalRenderer.prepareBackdrop(")&&v.contains("dockCompositor.drawFrame(")&&v.contains("renderCompositePass"));
    }''')
m(B+'Miuix307PassBlurGpuDemoTest.java','rotationResizesExistingProducerInPlaceWithoutNativeHotRebind','''    @Test public void rotationReplacesProducerGenerationInsteadOfReusingOldBufferQueue() throws Exception {
 String v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")); assertTrue(v.contains("replaceProducerGeneration(\"producer-generation-changed\")")&&v.contains("recreateInputProducer")&&v.contains("releaseInputProducer")&&v.contains("createInputProducer()"));
    }''')
m(B+'Miuix307PassBlurGpuDemoTest.java','stageBIsolatedBeforeUpstreamPrismalMaterial','''    @Test public void stageBIsolatedBeforeUpstreamPrismalMaterial() throws Exception {
 String v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")),a=Files.readString(MAIN.resolve("Miuix307PassBlurShaders.java")),p=Files.readString(Path.of("prismal/src/main/res/raw/prismal_fragment.glsl")); assertTrue(a.contains("uConfigRot")&&a.contains("uTexMatrix")); assertTrue(v.contains("OES_NORMALIZE_FRAGMENT")&&v.contains("prismalRenderer.prepareBackdrop(")&&v.contains("dockCompositor.drawFrame(")); assertFalse(p.contains("samplerExternalOES")||p.contains("uBackdropRect"));
    }''')
m(B+'Miuix307PrismalParityRepairTest.java','portablePrismalOwnsHalfResolutionTwoPassGaussianAndClearsTargets','''    @Test public void portablePrismalOwnsHalfResolutionTwoPassGaussianAndClearsTargets() throws Exception {
 String v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")),r=Files.readString(Path.of("prismal/src/main/java/com/hellovoid/prismal/PrismalRenderer.java")); assertTrue(v.contains("renderNormalizationPass")&&v.contains("prismalRenderer.prepareBackdrop(")&&v.contains("dockCompositor.drawFrame(")); assertTrue(r.contains("BLUR_FBO_SCALE = 0.5f")&&r.contains("blurFramebufferH")&&r.contains("blurFramebufferV")&&r.contains("glClear(GLES20.GL_COLOR_BUFFER_BIT)"));
    }''')
m(B+'Miuix307TextureViewPassBlurCalibrationTest.java','calibrationRotationResizesInputProducerWithoutGeometryHotUnbind','''    @Test public void calibrationRotationReplacesInputProducerGeneration() throws Exception {
 String v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")); assertTrue(v.contains("replaceProducerGeneration(\"producer-generation-changed\")")&&v.contains("releaseInputProducer")&&v.contains("createInputProducer()"));
    }''')
m(B+'Miuix307TextureViewPassBlurCalibrationTest.java','fullUpstreamPrismalOpticsRunAfterOesNormalizationWithoutLeavingGpuPath','''    @Test public void fullUpstreamPrismalOpticsRunAfterOesNormalizationWithoutLeavingGpuPath() throws Exception {
 String v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")),a=Files.readString(MAIN.resolve("Miuix307PassBlurShaders.java")); assertTrue(v.contains("OES_NORMALIZE_FRAGMENT")&&v.contains("prismalRenderer.prepareBackdrop(")&&v.contains("dockCompositor.drawFrame(")); assertTrue(a.contains("samplerExternalOES uTexture")&&a.contains("uBackdropRect")&&a.contains("uTexMatrix")); assertFalse(v.contains("glReadPixels")||v.contains("captureScreenAsync"));
    }''')
m(B+'Miuix307TextureViewStrongRefractionTest.java','portableRendererKeepsFramebufferAndGlassDomainsSeparateForPixelStableOptics','''    @Test public void portableRendererKeepsFramebufferAndGlassDomainsSeparateForPixelStableOptics() throws Exception {
 String v=view(),r=Files.readString(Path.of("prismal/src/main/java/com/hellovoid/prismal/PrismalRenderer.java")); assertTrue(v.contains("createPrismalGeometry(mapping)")&&v.contains("prismalRenderer.prepareBackdrop(")&&v.contains("dockCompositor.drawFrame(")); assertTrue(r.contains("u_resolution")&&r.contains("u_mousePos")&&r.contains("u_glassSize"));
    }''')
m(B+'PrismalModuleBoundaryContractTest.java','liquidDockAdapterOwnsOesNormalizationMappingLogAndFinalCrop','''    @Test public void liquidDockAdapterOwnsOesNormalizationMappingLogAndFinalCrop() throws Exception {
 String v=Files.readString(APP.resolve("Miuix307PassBlurTextureView.java")),c=Files.readString(APP.resolve("Miuix307PrismalCompositeShaders.java")); assertTrue(v.contains("OES_NORMALIZE_FRAGMENT")&&v.contains("prismalRenderer.prepareBackdrop(")&&v.contains("dockCompositor.drawFrame(")&&v.contains("renderNormalizationPass(mapping)")&&v.contains("renderCompositePass(prismalTexture, mapping)")&&v.contains("backdropSnapshot != mapping")); assertTrue(c.contains("uCropRect.xy + vUv * uCropRect.zw"));
    }''')
m(B+'WorkstationFullscreenProducerRecoveryContractTest.java','producerRebindDropsStaleFrameworkBindingAndWaitsForANewOesFrame','''    @Test public void producerRebindDropsStaleFrameworkBindingAndWaitsForANewOesFrame() throws Exception {
 String r=Files.readString(MAIN.resolve("Miuix307ZeroCopyRenderer.java")),v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")); assertTrue(r.contains("gpuBackdrop.replaceProducerGeneration(reason)")); assertTrue(v.contains("void replaceProducerGeneration(String reason)")&&v.contains("Miuix307PassBlurBridge.unbind(stale)")&&v.contains("hasConsumedFrame = false")&&v.contains("frameAvailable.set(false)"));
    }''')
m(B+'WorkstationFullscreenProducerRecoveryContractTest.java','producerRebindNeverReusesAnAlreadyParceledBufferQueueProducer','''    @Test public void producerRebindNeverReusesAnAlreadyParceledBufferQueueProducer() throws Exception {
 String v=Files.readString(MAIN.resolve("Miuix307PassBlurTextureView.java")); assertTrue(v.contains("recreateInputProducer")&&v.contains("releaseInputProducer(staleProducer, staleInput)")&&v.contains("producer.release()")&&v.contains("input.release()")&&v.contains("glDeleteTextures")&&v.contains("createInputProducer()")&&v.contains("PassBlur input producer was not replaced"));
    }''')
m(B+'config/ConfigCodecTest.java','absentPreferencesExportCompleteHistoricalDefaults','''    @Test public void absentPreferencesExportCompleteHistoricalDefaults() {
 Map<String,Object> e=ConfigCodec.exportValues(new HashMap<>()); assertEquals(141,e.size()); assertEquals(Boolean.FALSE,e.get("liquid_glass")); assertEquals(Boolean.TRUE,e.get("liquid_folder_glass")); assertFalse(e.containsKey("liquid_folder_corner_radius")); assertEquals(Boolean.TRUE,e.get("liquid_small_folder_glass")); assertEquals(Boolean.TRUE,e.get("liquid_large_folder_glass")); assertEquals(0.0d,((Number)e.get("liquid_icon_size_offset")).doubleValue(),.0001d); assertEquals(0.0d,((Number)e.get("liquid_widget_corner_radius")).doubleValue(),.0001d); assertEquals(0.0d,((Number)e.get("liquid_small_folder_corner_radius")).doubleValue(),.0001d); assertEquals(0.0d,((Number)e.get("liquid_large_folder_corner_radius")).doubleValue(),.0001d);
    }''')
(R/B/'LauncherGlassDragStyleContractTest.java').write_text('''package com.hellovoid.liquiddock;\nimport static org.junit.Assert.*; import java.nio.file.*; import org.junit.Test;\npublic class LauncherGlassDragStyleContractTest { @Test public void dragUsesOriginatingComponentStyleAndStyledLocalBounds() throws Exception { String n=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/LauncherGlassStaticNode.java")),h=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/MiuixLauncherDragOverlayHook.java")),o=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/LauncherGlassDragOverlay.java")),s=Files.readString(Path.of("src/main/java/com/hellovoid/liquiddock/LauncherGlassSinkView.java")); assertTrue(n.contains("GlassComponentStyle componentStyle()")); assertTrue(h.contains("resolved.style")&&h.contains("resolved.nodeKind")); assertTrue(o.contains("GlassComponentStyle style")&&o.contains("style.cornerRadiusDp")&&o.contains("style.sizeOffsetDp")); assertFalse(o.contains("folderCornerRadiusDp")); assertTrue(s.contains("setLocalVisualBounds")&&s.contains("localVisualLeft")&&s.contains("localVisualRight")); }}\n''')
print('scheme-a contracts patched; drag-style RED added')