from pathlib import Path

PATH = Path("src/main/java/com/hellovoid/liquiddock/LauncherGlassSession.java")
text = PATH.read_text()

old = '''    private void rebindProducer() {\n        if (shuttingDown) return;\n        Miuix307PassBlurBridge.Binding old = binding;\n        binding = null;\n        Miuix307PassBlurBridge.unbind(old);\n        backdropPrepared = false;\n        mainHandler.post(() -> bindProducerWhenReady(0));\n    }\n\n    private void renderScene(boolean rebuildBackdrop, boolean renderStatic, boolean renderDrag) {\n'''
new = '''    private void rebindProducer() {\n        if (shuttingDown) return;\n        Miuix307PassBlurBridge.Binding old = binding;\n        binding = null;\n        Miuix307PassBlurBridge.unbind(old);\n        backdropPrepared = false;\n        rollInputProducerForRebind();\n    }\n\n    private void rollInputProducerForRebind() {\n        if (shuttingDown) return;\n        postRender(() -> {\n            if (shuttingDown) return;\n            makePbufferCurrent();\n            releaseInputProducerEndpointOnRenderThread();\n            if (shuttingDown) return;\n            MainHook.log(TAG + " rolling PassBlur producer endpoint " + debugLabel());\n            createInputProducer();\n        }, null);\n    }\n\n    private void releaseInputProducerEndpointOnRenderThread() {\n        Surface producer = inputProducerSurface;\n        inputProducerSurface = null;\n        SurfaceTexture input = inputSurfaceTexture;\n        inputSurfaceTexture = null;\n\n        frameAvailable.set(false);\n        hasConsumedFrame = false;\n        consumedGeneration = -1L;\n        backdropPrepared = false;\n\n        if (input != null) {\n            try {\n                input.setOnFrameAvailableListener(null);\n            } catch (Throwable ignored) {\n            }\n        }\n        if (producer != null) {\n            try {\n                producer.release();\n            } catch (Throwable ignored) {\n            }\n        }\n        if (input != null) {\n            try {\n                input.release();\n            } catch (Throwable ignored) {\n            }\n        }\n        if (oesTexture != 0) {\n            GLES20.glDeleteTextures(1, new int[]{oesTexture}, 0);\n            oesTexture = 0;\n        }\n    }\n\n    private void renderScene(boolean rebuildBackdrop, boolean renderStatic, boolean renderDrag) {\n'''

count = text.count(old)
if count != 1:
    raise SystemExit(f"producer endpoint rollover: expected one rebind block, found {count}")
PATH.write_text(text.replace(old, new, 1))
print("Workspace PassBlur producer endpoint rollover patch applied")
