package com.hellovoid.liquiddock;

enum PassBlurDomain {
    LAUNCHER_WORKSPACE,
    SHORTCUT_POPUP,
    DRAG_OVERLAY,
    DOCK,
    SECURITY_CENTER,
    GBOARD_FLOATING,
    MIUI_SEARCHBOX,
    LOCKSCREEN_CLOCK,
    RECENTS_CAPSULE
}
