package com.hellovoid.liquiddock;

enum PassBlurDomain {
    LAUNCHER_WORKSPACE,
    SHORTCUT_POPUP,
    DRAG_OVERLAY,
    DOCK,
    SECURITY_CENTER,
    GBOARD_FLOATING,
    MIUI_SEARCHBOX,
    RECENTS_CAPSULE,
    SYSTEMUI_HANDLE_MENU,
    LAUNCHER_DIALOG
}
